import Head from "next/head";
import Image from "next/image";
import Hero from "@/components/Hero";
import { SliderData } from "@/components/SliderData";
import Slider from "@/components/Slider";
import Footer from "@/components/Footer";
import About from "@/components/About";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero heading="Transl-X AI" message="Language diversity should be bliss, not a barrier." />
    <About/>
    <Slider slides={SliderData}/>
    <Footer/>
    </>
  );
}
 